version: "3"
services: 
  php:
    build: .
    ports:
      - "8765:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes: 
      - ./sql/sde-latest.sql:/docker-entrypoint-initdb.d/00-sde.sql
      - ./sql/grant.sql:/docker-entrypoint-initdb.d/10-grant.sql
      - ./compression/table.sql:/docker-entrypoint-initdb.d/20-table.sql
    environment: 
      - MYSQL_DATABASE=eve
      - MYSQL_USER=eve
      - MYSQL_PASSWORD=eve
      - MYSQL_ROOT_PASSWORD=rabble